### ISSUE TITLE
Plugin Icons

### ISSUE THREAD

**Issue by dmhendricks** [markjaquith/wp-help#25]
I made some quick [plugin icons](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons).

They're **very basic** (only took me a minute). If you don't like them, feel free to close this issue (no hard feelings!). I just thought that they would look nicer than the auto-generated texture on WP.org.

Cheers,
Daniel

icon-128x128.png:
![icon-128x128](https://user-images.githubusercontent.com/8184361/42956132-d1f59b6a-8b44-11e8-80ec-c07a607ba37c.png)
icon-256x256.png:
![icon-256x256](https://user-images.githubusercontent.com/8184361/42956133-d20a94fc-8b44-11e8-8010-a28ee57e2a93.png)
icon.svg:
[![icon.svg.zip](https://f001.backblazeb2.com/file/hendricks/tmp/wp-help-icon.svg)](https://github.com/markjaquith/wp-help/files/2210777/icon.svg.zip)

**Comment by markjaquith** [comment]
These are GREAT. Thanks so much.
