### ISSUE TITLE
Improve Design/Readability of Documentation

### ISSUE THREAD

**Issue by mrwweb** [markjaquith/wp-help#26]
I love this plugin but have always felt the text is harder to read than it should be. I'd really love to make a pass at improving the styles. While I'm not sure the plugin needs to be completely Gutenbergified, I do think that looking at their default typography might be a good place to start. If I were to work on this, that's probably where I'd start.

It seems there isn't much activity around here these days and there are a number of outstanding PRs, so @markjaquith I'd appreciate some feedback/ideas/go-ahead before sinking much time into working on some styles.

**Comment by markjaquith** [comment]
Yes, I'd be open to this! I'll keep an eye out for your pull requests.

**Comment by mrwweb** [comment]
Closed via #27
