### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by TwisterMc** [markjaquith/wp-help#32]
I love WP Help and use it quite often, but it hasn't been updated in 2 years and that's a bit concerning. It still works, but is anyone keeping an eye on things regarding security or capability?  It's just nice to know if someone is at least paying attention.

**Comment by mrwweb** [comment]
See also: https://wordpress.org/support/topic/wp-help-abandoned-plugin/

**Comment by TwisterMc** [comment]
Might just need to fork it and update it ourselves.

**Comment by mrwweb** [comment]
@markjaquith Could you get us a status on this plugin? After our exchange on #26, I was optimistic about the future of this plugin! I was glad that the ensuing PR got accepted, but it never made it to the repo which now of course shows the "out of date" message and hides the plugin from the plugin searches.

There is clearly interest in this plugin and I'd love to look into more contributions like  #34, but I don't want to get ahead of myself if you've decided to retire the plugin.

**Comment by TwisterMc** [comment]
> Might just need to fork it and update it ourselves.

I started something new if anyone wants to help out. It's not a fork of this plugin, but something new. https://github.com/TwisterMc/help-docs

**Comment by markjaquith** [comment]
@mrwweb I’m working on a new release! The JS/CSS build system is old and busted, so I’m working on getting that modernized with Webpack 4 and Babel 7. Hoping to have a release out in the next week.

**Comment by markjaquith** [comment]
Slogged through the Webpack stuff (oof, that's complicated).

Version 1.6.1 is out!

**Comment by mrwweb** [comment]
@markjaquith Hooray! That is excellent news. FYI, for some reason, it seems that the plugin repo isn't picking up that you bumped the tested-to version or the minimum version. Therefore, the "hasn't been tested" message and repo search penalty still apply. My guess is that it's the [build status line in the readme.txt file](https://plugins.trac.wordpress.org/browser/wp-help/tags/1.6.1/readme.txt#L3).

**Comment by mrwweb** [comment]
Just to followup on my last comment, the tested up to and minimum version both appear correctly as of the 1.7.0 release.
